services:
  - type: web
    name: NIUMS1
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: DB_CHANNEL_ID
        sync: false
